# Generated by Django 5.2.1 on 2025-05-22 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='expiracion_enlace',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
