# Generated by Django 5.2.1 on 2025-05-22 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0002_documento_expiracion_enlace'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='fecha_expiracion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
