# Generated by Django 5.0.5 on 2025-05-31 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0003_documento_activo_documento_fecha_expiracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='is_shared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documento',
            name='size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
