# Generated by Django 5.2.1 on 2025-06-02 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0006_remove_documento_is_shared_remove_documento_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
