# Generated by Django 5.2.1 on 2025-06-06 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0007_perfilusuario_foto_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilprofesional',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='user',
        ),
        migrations.RemoveField(
            model_name='recordatorio',
            name='usuario',
        ),
        migrations.AddField(
            model_name='documento',
            name='is_shared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documento',
            name='size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='PerfilEmpresarial',
        ),
        migrations.DeleteModel(
            name='PerfilProfesional',
        ),
        migrations.DeleteModel(
            name='PerfilUsuario',
        ),
        migrations.DeleteModel(
            name='Recordatorio',
        ),
    ]
